#! /usr/bin/env ruby

require "rubygems"
require "matsuya"

aa = <<EOS
　　　(⌒)
　　 (　　) (⌒)
　　　 (⌒　)
　＿＿＿＿＿＿＿＿
　ヽxxx|XXXXXX|xxﾉ
　 |ooo|(ﾟДﾟ)|o|
　 ヽく(ﾉ(松)つノ
　　 ＼ヽニニ／
　　　└ＵＵ┘
EOS


#case Time.now.hour
case 0
when 6 .. 8
  order = Matsuya.order
  puts "おはようございます。朝ごはんは松屋の「#{order}」にしませんか？"

when 9 .. 12
  order = Matsuya.order
  puts "お疲れ様です。お昼ごはんは松屋の「#{order}」にしませんか？"

when 13 .. 15
  order = Matsuya.order
  puts "小腹が空きましたね。おやつは松屋で「#{order}」しませんか？"

when 16 .. 23
  order = Matsuya.order
  puts "そろそろ作業は終わりにして、松屋で「#{order}」しませんか？"

when 0 .. 5
  order = Matsuya.order 0.99
  puts "アヒャヒャヒャヒャ！松屋の「#{order}」！松屋の「#{order}」"
end

puts ""
puts aa
