#! /usr/bin/env ruby

require "rubygems"
require "matsuya"

aa = <<EOS
　　　(⌒)
　　 (　　) (⌒)
　　　 (⌒　)
　＿＿＿＿＿＿＿＿
　ヽxxx|XXXXXX|xxﾉ
　 |ooo|(ﾟДﾟ)|o|
　 ヽく(ﾉ(松)つノ
　　 ＼ヽニニ／
　　　└ＵＵ┘
EOS

order = Matsuya.order

case Time.now.hour
when 0 .. 8
  puts "おはようございます。朝ごはんは松屋の「#{order}」にしませんか？"

when 9 .. 12
  puts "お疲れ様です。お昼ごはんは松屋の「#{order}」にしませんか？"

when 13 .. 15
  puts "小腹が空きましたね。おやつは松屋で「#{order}」しませんか？"

when 16 .. 23
  puts "そろそろ作業は終わりにして、松屋で「#{order}」しませんか？"
end

puts ""
puts aa
